-- Create GROUP_EVENTS table
CREATE TABLE IF NOT EXISTS GROUP_EVENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_time DATETIME,
    created_by INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_group_events_group_id ON GROUP_EVENTS(group_id);
CREATE INDEX IF NOT EXISTS idx_group_events_created_by ON GROUP_EVENTS(created_by);
