-- Create GROUP_MEMBERS table
CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    role TEXT,
    is_accepted BOOLEAN DEFAULT 0,
    invited_by INTEGER,
    requested BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, user_id),
    FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (invited_by) REFERENCES USERS(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_group_members_group_id ON GROUP_MEMBERS(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON GROUP_MEMBERS(user_id);
