-- Create GROUP_POSTS table
CREATE TABLE IF NOT EXISTS GROUP_POSTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    content TEXT,
    image TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES GROUPS(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_group_posts_group_id ON GROUP_POSTS(group_id);
CREATE INDEX IF NOT EXISTS idx_group_posts_user_id ON GROUP_POSTS(user_id);
